/* Generated by Yosys 0.53 (git sha1 53c22ab7c, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "../../cfg_regs.sv:8.8" *)
module cfg_regs(clk, rst_n, cfg_addr, cfg_wdata, cfg_we, cfg_re, cfg_rdata, state, periph_en, idle_base_th, alpha, wake_mask, irq);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire [15:0] _004_;
  wire [63:0] _005_;
  wire [63:0] _006_;
  wire [63:0] _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire [31:0] _015_;
  wire [31:0] _016_;
  wire [3:0] _017_;
  wire _018_;
  wire _019_;
  wire [15:0] _020_;
  wire [15:0] _021_;
  wire [15:0] _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire [31:0] _026_;
  wire [3:0] _027_;
  wire [31:0] _028_;
  wire _029_;
  wire _030_;
  wire [1:0] _031_;
  wire [1:0] _032_;
  wire [1:0] _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire [31:0] _057_;
  wire [3:0] _058_;
  wire _059_;
  wire [31:0] _060_;
  (* src = "../../cfg_regs.sv:94.13-127.20" *)
  wire [3:0] _061_;
  (* src = "../../cfg_regs.sv:92.18-128.12" *)
  wire [3:0] _062_;
  wire [3:0] _063_;
  wire [1:0] _064_;
  wire [31:0] _065_;
  wire [15:0] _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  (* src = "../../cfg_regs.sv:137.18-181.12" *)
  wire [31:0] _075_;
  (* src = "../../cfg_regs.sv:167.25-169.28" *)
  wire [15:0] _076_;
  (* src = "../../cfg_regs.sv:164.21-178.24" *)
  wire [15:0] _077_;
  (* src = "../../cfg_regs.sv:141.13-180.20" *)
  wire [15:0] _078_;
  (* src = "../../cfg_regs.sv:175.25-177.28" *)
  wire [1:0] _079_;
  (* src = "../../cfg_regs.sv:172.26-178.24" *)
  wire [1:0] _080_;
  (* src = "../../cfg_regs.sv:121.25-123.28" *)
  wire [63:0] _081_;
  (* src = "../../cfg_regs.sv:118.21-124.24" *)
  wire [63:0] _082_;
  (* src = "../../cfg_regs.sv:94.13-127.20" *)
  wire [63:0] _083_;
  (* src = "../../cfg_regs.sv:92.18-128.12" *)
  wire [63:0] _084_;
  (* src = "../../cfg_regs.sv:94.13-127.20" *)
  wire [3:0] _085_;
  (* src = "../../cfg_regs.sv:92.18-128.12" *)
  wire [3:0] _086_;
  (* src = "../../cfg_regs.sv:94.13-127.20" *)
  wire [3:0] _087_;
  (* src = "../../cfg_regs.sv:92.18-128.12" *)
  wire [3:0] _088_;
  (* src = "../../cfg_regs.sv:211.26-213.20" *)
  wire _089_;
  (* src = "../../cfg_regs.sv:209.17-213.20" *)
  wire _090_;
  (* src = "../../cfg_regs.sv:211.26-213.20" *)
  wire _091_;
  (* src = "../../cfg_regs.sv:209.17-213.20" *)
  wire _092_;
  (* src = "../../cfg_regs.sv:211.26-213.20" *)
  wire _093_;
  (* src = "../../cfg_regs.sv:209.17-213.20" *)
  wire _094_;
  (* src = "../../cfg_regs.sv:211.26-213.20" *)
  wire _095_;
  (* src = "../../cfg_regs.sv:209.17-213.20" *)
  wire _096_;
  (* src = "../../cfg_regs.sv:94.13-127.20" *)
  wire [3:0] _097_;
  (* src = "../../cfg_regs.sv:92.18-128.12" *)
  wire [3:0] _098_;
  wire _099_;
  wire [1:0] _100_;
  wire _101_;
  wire [1:0] _102_;
  wire _103_;
  wire [1:0] _104_;
  wire _105_;
  wire [1:0] _106_;
  wire _107_;
  wire _108_;
  wire [1:0] _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire [1:0] _115_;
  wire _116_;
  wire _117_;
  wire [3:0] _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire [3:0] _124_;
  wire _125_;
  wire [31:0] _126_;
  wire _127_;
  wire [63:0] _128_;
  wire _129_;
  wire [63:0] _130_;
  wire _131_;
  wire [63:0] _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire [63:0] _139_;
  wire _140_;
  wire [63:0] _141_;
  wire _142_;
  wire [63:0] _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire [63:0] _150_;
  wire _151_;
  wire [3:0] _152_;
  wire _153_;
  wire [3:0] _154_;
  wire _155_;
  wire [3:0] _156_;
  wire _157_;
  wire [3:0] _158_;
  wire _159_;
  wire [3:0] _160_;
  wire _161_;
  wire [3:0] _162_;
  wire _163_;
  wire [3:0] _164_;
  wire _165_;
  wire _166_;
  wire [3:0] _167_;
  wire _168_;
  wire [63:0] _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire [63:0] _176_;
  wire _177_;
  wire [3:0] _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire [3:0] _182_;
  wire _183_;
  wire [3:0] _184_;
  wire _185_;
  wire [3:0] _186_;
  wire _187_;
  wire [3:0] _188_;
  wire _189_;
  wire _190_;
  wire [3:0] _191_;
  wire _192_;
  wire [63:0] _193_;
  wire _194_;
  wire [3:0] _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire [11:0] _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire [11:0] _214_;
  wire _215_;
  wire [1:0] _216_;
  wire _217_;
  wire _218_;
  wire [1:0] _219_;
  wire _220_;
  wire [1:0] _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire [1:0] _228_;
  wire _229_;
  wire [13:0] _230_;
  wire _231_;
  wire [13:0] _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire [13:0] _238_;
  wire _239_;
  wire [15:0] _240_;
  wire _241_;
  wire [15:0] _242_;
  wire _243_;
  wire [15:0] _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire [15:0] _250_;
  wire _251_;
  wire _252_;
  wire [1:0] _253_;
  wire _254_;
  wire [1:0] _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  (* src = "../../cfg_regs.sv:94.13-127.20" *)
  wire [3:0] _261_;
  (* src = "../../cfg_regs.sv:92.18-128.12" *)
  wire [3:0] _262_;
  (* src = "../../cfg_regs.sv:31.37" *)
  output [3:0] alpha;
  wire [3:0] alpha;
  (* src = "../../cfg_regs.sv:68.30" *)
  reg [3:0] alpha_reg;
  (* src = "../../cfg_regs.sv:19.37" *)
  input [7:0] cfg_addr;
  wire [7:0] cfg_addr;
  (* src = "../../cfg_regs.sv:23.37" *)
  output [31:0] cfg_rdata;
  reg [31:0] cfg_rdata;
  (* src = "../../cfg_regs.sv:22.37" *)
  input cfg_re;
  wire cfg_re;
  (* src = "../../cfg_regs.sv:20.37" *)
  input [31:0] cfg_wdata;
  wire [31:0] cfg_wdata;
  (* src = "../../cfg_regs.sv:21.37" *)
  input cfg_we;
  wire cfg_we;
  (* src = "../../cfg_regs.sv:15.37" *)
  input clk;
  wire clk;
  (* src = "../../cfg_regs.sv:30.37" *)
  output [63:0] idle_base_th;
  wire [63:0] idle_base_th;
  (* src = "../../cfg_regs.sv:67.30" *)
  reg [63:0] idle_base_th_reg;
  (* src = "../../cfg_regs.sv:35.37" *)
  output irq;
  wire irq;
  (* src = "../../cfg_regs.sv:70.30" *)
  reg [3:0] irq_mask_reg;
  (* src = "../../cfg_regs.sv:71.30" *)
  reg [3:0] irq_status_reg;
  (* src = "../../cfg_regs.sv:29.37" *)
  output [3:0] periph_en;
  wire [3:0] periph_en;
  (* src = "../../cfg_regs.sv:66.30" *)
  reg [3:0] periph_en_reg;
  (* src = "../../cfg_regs.sv:16.37" *)
  input rst_n;
  wire rst_n;
  (* src = "../../cfg_regs.sv:26.37" *)
  input [7:0] state;
  wire [7:0] state;
  (* src = "../../cfg_regs.sv:75.30" *)
  wire [3:0] state_changed;
  (* src = "../../cfg_regs.sv:74.30" *)
  reg [7:0] state_prev;
  (* src = "../../cfg_regs.sv:32.37" *)
  output [3:0] wake_mask;
  wire [3:0] wake_mask;
  (* src = "../../cfg_regs.sv:69.30" *)
  reg [3:0] wake_mask_reg;
  assign _008_ = ! rst_n;
  assign _000_ = $signed(_060_) < (* src = "../../cfg_regs.sv:121.29-121.36" *) $signed(32'd4);
  assign _001_ = $signed(_060_) < (* src = "../../cfg_regs.sv:122.29-122.70" *) $signed(4'h4);
  assign _002_ = $signed(_060_) >= (* src = "../../cfg_regs.sv:122.29-122.70" *) $signed(1'h0);
  assign _003_ = _002_ && (* src = "../../cfg_regs.sv:122.29-122.70" *) _001_;
  assign _004_ = _003_ ? (* src = "../../cfg_regs.sv:122.29-122.70" *) 16'hffff : 16'h0000;
  (* src = "../../cfg_regs.sv:122.29-122.70" *)
  \$bwmux  #(
    .WIDTH(32'd64)
  ) _269_ (
    .A(idle_base_th_reg),
    .B({ cfg_wdata[15:0], cfg_wdata[15:0], cfg_wdata[15:0], cfg_wdata[15:0] }),
    .S(_006_),
    .Y(_007_)
  );
  assign _017_ = ~ (* src = "../../cfg_regs.sv:113.56-113.73" *) cfg_wdata[3:0];
  assign _010_ = ! rst_n;
  assign _012_ = cfg_addr >= (* src = "../../cfg_regs.sv:164.26-164.55" *) 8'h10;
  assign _013_ = { 24'h000000, cfg_addr } < (* src = "../../cfg_regs.sv:165.26-165.64" *) 32'd32;
  assign _014_ = _012_ && (* src = "../../cfg_regs.sv:164.25-165.65" *) _013_;
  assign _015_ = { 24'h000000, cfg_addr } - (* src = "../../cfg_regs.sv:166.46-166.74" *) 32'd16;
  assign _027_ = irq_status_reg & (* src = "../../cfg_regs.sv:113.39-113.73" *) _017_;
  assign _018_ = $signed(_016_) < (* src = "../../cfg_regs.sv:167.29-167.36" *) $signed(32'd4);
  assign _019_ = $signed(_016_) < (* src = "../../cfg_regs.sv:168.49-168.70" *) $signed(4'h4);
  assign _021_ = _019_ ? (* src = "../../cfg_regs.sv:168.49-168.70" *) _020_ : 16'hxxxx;
  assign _023_ = cfg_addr >= (* src = "../../cfg_regs.sv:172.31-172.58" *) 8'h80;
  assign _024_ = { 24'h000000, cfg_addr } < (* src = "../../cfg_regs.sv:173.31-173.67" *) 32'd144;
  assign _025_ = _023_ && (* src = "../../cfg_regs.sv:172.30-173.68" *) _024_;
  assign _026_ = { 24'h000000, cfg_addr } - (* src = "../../cfg_regs.sv:174.46-174.72" *) 32'd128;
  assign _034_ = cfg_addr >= (* src = "../../cfg_regs.sv:118.26-118.55" *) 8'h10;
  assign _029_ = $signed(_028_) < (* src = "../../cfg_regs.sv:175.29-175.36" *) $signed(32'd4);
  assign _030_ = $signed(_028_) < (* src = "../../cfg_regs.sv:176.47-176.57" *) $signed(4'h4);
  assign _032_ = _030_ ? (* src = "../../cfg_regs.sv:176.47-176.57" *) _031_ : 2'hx;
  assign _041_ = { 24'h000000, cfg_addr } < (* src = "../../cfg_regs.sv:119.26-119.64" *) 32'd32;
  assign _035_ = ! rst_n;
  assign _037_ = state[1:0] != (* src = "../../cfg_regs.sv:198.33-198.58" *) state_prev[1:0];
  assign _038_ = state[3:2] != (* src = "../../cfg_regs.sv:198.33-198.58" *) state_prev[3:2];
  assign _039_ = state[5:4] != (* src = "../../cfg_regs.sv:198.33-198.58" *) state_prev[5:4];
  assign _040_ = state[7:6] != (* src = "../../cfg_regs.sv:198.33-198.58" *) state_prev[7:6];
  assign _050_ = _034_ && (* src = "../../cfg_regs.sv:118.25-119.65" *) _041_;
  assign _042_ = ! rst_n;
  assign _044_ = cfg_addr == (* src = "../../cfg_regs.sv:211.41-211.68" *) 8'hc0;
  assign _045_ = cfg_we && (* src = "../../cfg_regs.sv:211.30-211.69" *) _044_;
  assign _046_ = _045_ && (* src = "../../cfg_regs.sv:211.30-211.85" *) cfg_wdata[0];
  assign _047_ = cfg_addr == (* src = "../../cfg_regs.sv:211.41-211.68" *) 8'hc0;
  assign _048_ = cfg_we && (* src = "../../cfg_regs.sv:211.30-211.69" *) _047_;
  assign _049_ = _048_ && (* src = "../../cfg_regs.sv:211.30-211.85" *) cfg_wdata[1];
  assign _057_ = { 24'h000000, cfg_addr } - (* src = "../../cfg_regs.sv:120.46-120.74" *) 32'd16;
  assign _051_ = cfg_addr == (* src = "../../cfg_regs.sv:211.41-211.68" *) 8'hc0;
  assign _052_ = cfg_we && (* src = "../../cfg_regs.sv:211.30-211.69" *) _051_;
  assign _053_ = _052_ && (* src = "../../cfg_regs.sv:211.30-211.85" *) cfg_wdata[2];
  assign _054_ = cfg_addr == (* src = "../../cfg_regs.sv:211.41-211.68" *) 8'hc0;
  assign _055_ = cfg_we && (* src = "../../cfg_regs.sv:211.30-211.69" *) _054_;
  assign _056_ = _055_ && (* src = "../../cfg_regs.sv:211.30-211.85" *) cfg_wdata[3];
  assign _058_ = irq_status_reg & (* src = "../../cfg_regs.sv:219.20-219.49" *) irq_mask_reg;
  assign _059_ = | (* src = "../../cfg_regs.sv:219.18-219.50" *) _058_;
  assign _063_[1:0] = _028_[0] ? (* src = "../../cfg_regs.sv:176.47-176.57" *) state[3:2] : state[1:0];
  assign _063_[3:2] = _028_[0] ? (* src = "../../cfg_regs.sv:176.47-176.57" *) state[7:6] : state[5:4];
  assign _064_ = _028_[1] ? (* src = "../../cfg_regs.sv:176.47-176.57" *) _063_[3:2] : _063_[1:0];
  assign _065_[15:0] = _016_[0] ? (* src = "../../cfg_regs.sv:168.49-168.70" *) idle_base_th_reg[31:16] : idle_base_th_reg[15:0];
  assign _065_[31:16] = _016_[0] ? (* src = "../../cfg_regs.sv:168.49-168.70" *) idle_base_th_reg[63:48] : idle_base_th_reg[47:32];
  assign _066_ = _016_[1] ? (* src = "../../cfg_regs.sv:168.49-168.70" *) _065_[31:16] : _065_[15:0];
  assign _067_ = _060_[1:0] == (* src = "../../cfg_regs.sv:122.29-122.70" *) 2'h0;
  assign _068_ = _060_[1:0] == (* src = "../../cfg_regs.sv:122.29-122.70" *) 2'h1;
  assign _069_ = _060_[1:0] == (* src = "../../cfg_regs.sv:122.29-122.70" *) 2'h2;
  assign _070_ = _060_[1:0] == (* src = "../../cfg_regs.sv:122.29-122.70" *) 2'h3;
  assign _071_ = _060_[1:0] == (* src = "../../cfg_regs.sv:122.29-122.70" *) 2'h0;
  assign _072_ = _060_[1:0] == (* src = "../../cfg_regs.sv:122.29-122.70" *) 2'h1;
  assign _073_ = _060_[1:0] == (* src = "../../cfg_regs.sv:122.29-122.70" *) 2'h2;
  assign _074_ = _060_[1:0] == (* src = "../../cfg_regs.sv:122.29-122.70" *) 2'h3;
  assign _006_[15:0] = _067_ ? (* src = "../../cfg_regs.sv:122.29-122.70" *) _004_ : 16'h0000;
  assign _006_[31:16] = _068_ ? (* src = "../../cfg_regs.sv:122.29-122.70" *) _004_ : 16'h0000;
  assign _006_[47:32] = _069_ ? (* src = "../../cfg_regs.sv:122.29-122.70" *) _004_ : 16'h0000;
  assign _006_[63:48] = _070_ ? (* src = "../../cfg_regs.sv:122.29-122.70" *) _004_ : 16'h0000;
  assign _005_[15:0] = _071_ ? (* src = "../../cfg_regs.sv:122.29-122.70" *) _004_ : 16'h0000;
  assign _005_[31:16] = _072_ ? (* src = "../../cfg_regs.sv:122.29-122.70" *) _004_ : 16'h0000;
  assign _005_[47:32] = _073_ ? (* src = "../../cfg_regs.sv:122.29-122.70" *) _004_ : 16'h0000;
  assign _005_[63:48] = _074_ ? (* src = "../../cfg_regs.sv:122.29-122.70" *) _004_ : 16'h0000;
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) alpha_reg <= 4'h8;
    else alpha_reg <= _062_;
  (* src = "../../cfg_regs.sv:134.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) cfg_rdata <= 32'd0;
    else cfg_rdata <= _075_;
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[15:0] <= 16'h03e8;
    else idle_base_th_reg[15:0] <= _084_[15:0];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[31:16] <= 16'h03e8;
    else idle_base_th_reg[31:16] <= _084_[31:16];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[47:32] <= 16'h03e8;
    else idle_base_th_reg[47:32] <= _084_[47:32];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[63:48] <= 16'h03e8;
    else idle_base_th_reg[63:48] <= _084_[63:48];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) irq_mask_reg <= 4'h0;
    else irq_mask_reg <= _086_;
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) irq_status_reg <= 4'h0;
    else irq_status_reg <= _088_;
  (* src = "../../cfg_regs.sv:203.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) irq_status_reg <= 4'h0;
    else irq_status_reg <= { _096_, _094_, _092_, _090_ };
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) periph_en_reg <= 4'h0;
    else periph_en_reg <= _098_;
  (* src = "../../cfg_regs.sv:187.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_prev[1:0] <= 2'h0;
    else state_prev[1:0] <= state[1:0];
  (* src = "../../cfg_regs.sv:187.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_prev[3:2] <= 2'h0;
    else state_prev[3:2] <= state[3:2];
  (* src = "../../cfg_regs.sv:187.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_prev[5:4] <= 2'h0;
    else state_prev[5:4] <= state[5:4];
  (* src = "../../cfg_regs.sv:187.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_prev[7:6] <= 2'h0;
    else state_prev[7:6] <= state[7:6];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) wake_mask_reg <= 4'hf;
    else wake_mask_reg <= _262_;
  assign _181_ = _203_ ? (* src = "../../cfg_regs.sv:212.21-212.47|../../cfg_regs.sv:211.26-213.20" *) 1'h0 : irq_status_reg[3];
  assign _108_ = _117_ ? (* src = "../../cfg_regs.sv:212.21-212.47|../../cfg_regs.sv:211.26-213.20" *) 1'h0 : irq_status_reg[2];
  assign _099_ = ! (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:143.21-143.55|../../cfg_regs.sv:141.13-180.20" *) cfg_addr;
  assign _100_ = _101_ ? (* src = "../../cfg_regs.sv:137.30-181.12|../../cfg_regs.sv:137.18-181.12" *) _255_ : 2'hx;
  assign _102_ = _103_ ? (* src = "../../cfg_regs.sv:176.29-176.58|../../cfg_regs.sv:175.25-177.28" *) _033_ : 2'h0;
  assign _104_ = _105_ ? (* src = "../../cfg_regs.sv:173.70-178.24|../../cfg_regs.sv:172.26-178.24" *) _102_ : 2'hx;
  assign _106_ = _107_ ? (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:165.67-170.24|../../cfg_regs.sv:164.21-178.24" *) 2'hx : _104_;
  function [1:0] _355_;
    input [1:0] a;
    input [9:0] b;
    input [4:0] s;
    (* full_case = 32'd1 *)
    (* src = "../../cfg_regs.sv:159.21-159.56|../../cfg_regs.sv:141.13-180.20" *)
    (* parallel_case *)
    casez (s)
      5'b????1:
        _355_ = b[1:0];
      5'b???1?:
        _355_ = b[3:2];
      5'b??1??:
        _355_ = b[5:4];
      5'b?1???:
        _355_ = b[7:6];
      5'b1????:
        _355_ = b[9:8];
      default:
        _355_ = a;
    endcase
  endfunction
  assign _109_ = _355_(_106_, 10'hxxx, { _114_, _113_, _112_, _111_, _110_ });
  assign _110_ = cfg_addr == (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:159.21-159.56|../../cfg_regs.sv:141.13-180.20" *) 8'hc0;
  assign _111_ = cfg_addr == (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:155.21-155.54|../../cfg_regs.sv:141.13-180.20" *) 8'h0c;
  assign _112_ = cfg_addr == (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:151.21-151.55|../../cfg_regs.sv:141.13-180.20" *) 8'h08;
  assign _113_ = cfg_addr == (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:147.21-147.49|../../cfg_regs.sv:141.13-180.20" *) 8'h04;
  assign _114_ = ! (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:143.21-143.55|../../cfg_regs.sv:141.13-180.20" *) cfg_addr;
  assign _115_ = _116_ ? (* src = "../../cfg_regs.sv:137.30-181.12|../../cfg_regs.sv:137.18-181.12" *) _109_ : 2'hx;
  function [3:0] _362_;
    input [3:0] a;
    input [19:0] b;
    input [4:0] s;
    (* full_case = 32'd1 *)
    (* src = "../../cfg_regs.sv:159.21-159.56|../../cfg_regs.sv:141.13-180.20" *)
    (* parallel_case *)
    casez (s)
      5'b????1:
        _362_ = b[3:0];
      5'b???1?:
        _362_ = b[7:4];
      5'b??1??:
        _362_ = b[11:8];
      5'b?1???:
        _362_ = b[15:12];
      5'b1????:
        _362_ = b[19:16];
      default:
        _362_ = a;
    endcase
  endfunction
  assign _118_ = _362_(_077_[3:0], { periph_en_reg, alpha_reg, wake_mask_reg, irq_mask_reg, irq_status_reg }, { _123_, _122_, _121_, _120_, _119_ });
  assign _119_ = cfg_addr == (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:159.21-159.56|../../cfg_regs.sv:141.13-180.20" *) 8'hc0;
  assign _120_ = cfg_addr == (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:155.21-155.54|../../cfg_regs.sv:141.13-180.20" *) 8'h0c;
  assign _121_ = cfg_addr == (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:151.21-151.55|../../cfg_regs.sv:141.13-180.20" *) 8'h08;
  assign _122_ = cfg_addr == (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:147.21-147.49|../../cfg_regs.sv:141.13-180.20" *) 8'h04;
  assign _123_ = ! (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:143.21-143.55|../../cfg_regs.sv:141.13-180.20" *) cfg_addr;
  assign _124_ = _125_ ? (* src = "../../cfg_regs.sv:137.30-181.12|../../cfg_regs.sv:137.18-181.12" *) _118_ : 4'hx;
  assign _135_ = _144_ ? (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:210.21-210.47|../../cfg_regs.sv:209.17-213.20" *) 1'hx : _108_;
  assign _126_ = _127_ ? (* src = "../../cfg_regs.sv:137.30-181.12|../../cfg_regs.sv:137.18-181.12" *) { 16'h0000, _078_ } : cfg_rdata;
  assign _128_ = _129_ ? (* src = "../../cfg_regs.sv:122.29-122.71|../../cfg_regs.sv:121.25-123.28" *) _007_ : idle_base_th_reg;
  assign _130_ = _131_ ? (* src = "../../cfg_regs.sv:119.67-124.24|../../cfg_regs.sv:118.21-124.24" *) _128_ : 64'hxxxxxxxxxxxxxxxx;
  function [63:0] _373_;
    input [63:0] a;
    input [319:0] b;
    input [4:0] s;
    (* full_case = 32'd1 *)
    (* src = "../../cfg_regs.sv:113.21-113.74|../../cfg_regs.sv:94.13-127.20" *)
    (* parallel_case *)
    casez (s)
      5'b????1:
        _373_ = b[63:0];
      5'b???1?:
        _373_ = b[127:64];
      5'b??1??:
        _373_ = b[191:128];
      5'b?1???:
        _373_ = b[255:192];
      5'b1????:
        _373_ = b[319:256];
      default:
        _373_ = a;
    endcase
  endfunction
  assign _132_ = _373_(_130_, 320'hxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx, { _138_, _137_, _136_, _134_, _133_ });
  assign _133_ = cfg_addr == (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:113.21-113.74|../../cfg_regs.sv:94.13-127.20" *) 8'hc0;
  assign _134_ = cfg_addr == (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:108.21-108.54|../../cfg_regs.sv:94.13-127.20" *) 8'h0c;
  assign _136_ = cfg_addr == (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:104.21-104.55|../../cfg_regs.sv:94.13-127.20" *) 8'h08;
  assign _137_ = cfg_addr == (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:100.21-100.49|../../cfg_regs.sv:94.13-127.20" *) 8'h04;
  assign _138_ = ! (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:96.21-96.55|../../cfg_regs.sv:94.13-127.20" *) cfg_addr;
  assign _139_ = _140_ ? (* src = "../../cfg_regs.sv:94.13-127.20|../../cfg_regs.sv:92.18-128.12" *) _132_ : 64'hxxxxxxxxxxxxxxxx;
  assign _141_ = _142_ ? (* src = "../../cfg_regs.sv:119.67-124.24|../../cfg_regs.sv:118.21-124.24" *) _081_ : idle_base_th_reg;
  function [63:0] _381_;
    input [63:0] a;
    input [319:0] b;
    input [4:0] s;
    (* full_case = 32'd1 *)
    (* src = "../../cfg_regs.sv:113.21-113.74|../../cfg_regs.sv:94.13-127.20" *)
    (* parallel_case *)
    casez (s)
      5'b????1:
        _381_ = b[63:0];
      5'b???1?:
        _381_ = b[127:64];
      5'b??1??:
        _381_ = b[191:128];
      5'b?1???:
        _381_ = b[255:192];
      5'b1????:
        _381_ = b[319:256];
      default:
        _381_ = a;
    endcase
  endfunction
  assign _143_ = _381_(_141_, 320'hxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx, { _149_, _148_, _147_, _146_, _145_ });
  assign _145_ = cfg_addr == (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:113.21-113.74|../../cfg_regs.sv:94.13-127.20" *) 8'hc0;
  assign _146_ = cfg_addr == (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:108.21-108.54|../../cfg_regs.sv:94.13-127.20" *) 8'h0c;
  assign _147_ = cfg_addr == (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:104.21-104.55|../../cfg_regs.sv:94.13-127.20" *) 8'h08;
  assign _148_ = cfg_addr == (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:100.21-100.49|../../cfg_regs.sv:94.13-127.20" *) 8'h04;
  assign _149_ = ! (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:96.21-96.55|../../cfg_regs.sv:94.13-127.20" *) cfg_addr;
  assign _150_ = _151_ ? (* src = "../../cfg_regs.sv:94.13-127.20|../../cfg_regs.sv:92.18-128.12" *) _143_ : 64'hxxxxxxxxxxxxxxxx;
  assign _152_ = _153_ ? (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:113.21-113.74|../../cfg_regs.sv:94.13-127.20" *) _027_ : irq_status_reg;
  assign _153_ = cfg_addr == (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:113.21-113.74|../../cfg_regs.sv:94.13-127.20" *) 8'hc0;
  assign _154_ = _155_ ? (* src = "../../cfg_regs.sv:94.13-127.20|../../cfg_regs.sv:92.18-128.12" *) _152_ : 4'hx;
  assign _156_ = _157_ ? (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:108.21-108.54|../../cfg_regs.sv:94.13-127.20" *) cfg_wdata[3:0] : irq_mask_reg;
  assign _157_ = cfg_addr == (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:108.21-108.54|../../cfg_regs.sv:94.13-127.20" *) 8'h0c;
  assign _158_ = _159_ ? (* src = "../../cfg_regs.sv:94.13-127.20|../../cfg_regs.sv:92.18-128.12" *) _156_ : 4'hx;
  assign _165_ = _174_ ? (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:210.21-210.47|../../cfg_regs.sv:209.17-213.20" *) 1'h1 : _093_;
  assign _160_ = _161_ ? (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:104.21-104.55|../../cfg_regs.sv:94.13-127.20" *) cfg_wdata[3:0] : wake_mask_reg;
  assign _161_ = cfg_addr == (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:104.21-104.55|../../cfg_regs.sv:94.13-127.20" *) 8'h08;
  assign _162_ = _163_ ? (* src = "../../cfg_regs.sv:94.13-127.20|../../cfg_regs.sv:92.18-128.12" *) _160_ : 4'hx;
  assign _164_ = _166_ ? (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:100.21-100.49|../../cfg_regs.sv:94.13-127.20" *) cfg_wdata[3:0] : alpha_reg;
  assign _166_ = cfg_addr == (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:100.21-100.49|../../cfg_regs.sv:94.13-127.20" *) 8'h04;
  assign _167_ = _168_ ? (* src = "../../cfg_regs.sv:94.13-127.20|../../cfg_regs.sv:92.18-128.12" *) _164_ : 4'hx;
  function [63:0] _401_;
    input [63:0] a;
    input [319:0] b;
    input [4:0] s;
    (* full_case = 32'd1 *)
    (* src = "../../cfg_regs.sv:113.21-113.74|../../cfg_regs.sv:94.13-127.20" *)
    (* parallel_case *)
    casez (s)
      5'b????1:
        _401_ = b[63:0];
      5'b???1?:
        _401_ = b[127:64];
      5'b??1??:
        _401_ = b[191:128];
      5'b?1???:
        _401_ = b[255:192];
      5'b1????:
        _401_ = b[319:256];
      default:
        _401_ = a;
    endcase
  endfunction
  assign _169_ = _401_(_082_, { idle_base_th_reg, idle_base_th_reg, idle_base_th_reg, idle_base_th_reg, idle_base_th_reg }, { _175_, _173_, _172_, _171_, _170_ });
  assign _170_ = cfg_addr == (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:113.21-113.74|../../cfg_regs.sv:94.13-127.20" *) 8'hc0;
  assign _171_ = cfg_addr == (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:108.21-108.54|../../cfg_regs.sv:94.13-127.20" *) 8'h0c;
  assign _172_ = cfg_addr == (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:104.21-104.55|../../cfg_regs.sv:94.13-127.20" *) 8'h08;
  assign _173_ = cfg_addr == (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:100.21-100.49|../../cfg_regs.sv:94.13-127.20" *) 8'h04;
  assign _180_ = _189_ ? (* src = "../../cfg_regs.sv:212.21-212.47|../../cfg_regs.sv:211.26-213.20" *) 1'h0 : irq_status_reg[1];
  assign _175_ = ! (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:96.21-96.55|../../cfg_regs.sv:94.13-127.20" *) cfg_addr;
  assign _176_ = _177_ ? (* src = "../../cfg_regs.sv:94.13-127.20|../../cfg_regs.sv:92.18-128.12" *) _169_ : 64'hxxxxxxxxxxxxxxxx;
  assign _178_ = _179_ ? (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:96.21-96.55|../../cfg_regs.sv:94.13-127.20" *) cfg_wdata[3:0] : periph_en_reg;
  assign _179_ = ! (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:96.21-96.55|../../cfg_regs.sv:94.13-127.20" *) cfg_addr;
  assign _182_ = _183_ ? (* src = "../../cfg_regs.sv:94.13-127.20|../../cfg_regs.sv:92.18-128.12" *) _178_ : 4'hx;
  assign _184_ = _185_ ? (* src = "../../cfg_regs.sv:94.13-127.20|../../cfg_regs.sv:92.18-128.12" *) _087_ : irq_status_reg;
  assign _186_ = _187_ ? (* src = "../../cfg_regs.sv:94.13-127.20|../../cfg_regs.sv:92.18-128.12" *) _085_ : irq_mask_reg;
  assign _188_ = _190_ ? (* src = "../../cfg_regs.sv:94.13-127.20|../../cfg_regs.sv:92.18-128.12" *) _261_ : wake_mask_reg;
  assign _191_ = _192_ ? (* src = "../../cfg_regs.sv:94.13-127.20|../../cfg_regs.sv:92.18-128.12" *) _061_ : alpha_reg;
  assign _193_ = _194_ ? (* src = "../../cfg_regs.sv:94.13-127.20|../../cfg_regs.sv:92.18-128.12" *) _083_ : idle_base_th_reg;
  assign _195_ = _196_ ? (* src = "../../cfg_regs.sv:94.13-127.20|../../cfg_regs.sv:92.18-128.12" *) _097_ : periph_en_reg;
  assign _197_ = _198_ ? (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:210.21-210.47|../../cfg_regs.sv:209.17-213.20" *) 1'hx : _180_;
  assign _199_ = _200_ ? (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:210.21-210.47|../../cfg_regs.sv:209.17-213.20" *) 1'h1 : _091_;
  assign _201_ = _202_ ? (* src = "../../cfg_regs.sv:212.21-212.47|../../cfg_regs.sv:211.26-213.20" *) 1'h0 : irq_status_reg[0];
  assign _204_ = _205_ ? (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:210.21-210.47|../../cfg_regs.sv:209.17-213.20" *) 1'hx : _201_;
  assign _206_ = _207_ ? (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:210.21-210.47|../../cfg_regs.sv:209.17-213.20" *) 1'h1 : _089_;
  function [11:0] _423_;
    input [11:0] a;
    input [59:0] b;
    input [4:0] s;
    (* full_case = 32'd1 *)
    (* src = "../../cfg_regs.sv:159.21-159.56|../../cfg_regs.sv:141.13-180.20" *)
    (* parallel_case *)
    casez (s)
      5'b????1:
        _423_ = b[11:0];
      5'b???1?:
        _423_ = b[23:12];
      5'b??1??:
        _423_ = b[35:24];
      5'b?1???:
        _423_ = b[47:36];
      5'b1????:
        _423_ = b[59:48];
      default:
        _423_ = a;
    endcase
  endfunction
  assign _208_ = _423_(_077_[15:4], 60'h000000000000000, { _213_, _212_, _211_, _210_, _209_ });
  assign _218_ = _227_ ? (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:210.21-210.47|../../cfg_regs.sv:209.17-213.20" *) 1'hx : _181_;
  assign _209_ = cfg_addr == (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:159.21-159.56|../../cfg_regs.sv:141.13-180.20" *) 8'hc0;
  assign _210_ = cfg_addr == (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:155.21-155.54|../../cfg_regs.sv:141.13-180.20" *) 8'h0c;
  assign _211_ = cfg_addr == (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:151.21-151.55|../../cfg_regs.sv:141.13-180.20" *) 8'h08;
  assign _212_ = cfg_addr == (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:147.21-147.49|../../cfg_regs.sv:141.13-180.20" *) 8'h04;
  assign _213_ = ! (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:143.21-143.55|../../cfg_regs.sv:141.13-180.20" *) cfg_addr;
  assign _214_ = _215_ ? (* src = "../../cfg_regs.sv:137.30-181.12|../../cfg_regs.sv:137.18-181.12" *) _208_ : 12'hxxx;
  assign _216_ = _217_ ? (* src = "../../cfg_regs.sv:173.70-178.24|../../cfg_regs.sv:172.26-178.24" *) _079_ : 2'h0;
  assign _219_ = _220_ ? (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:165.67-170.24|../../cfg_regs.sv:164.21-178.24" *) 2'hx : _216_;
  function [1:0] _433_;
    input [1:0] a;
    input [9:0] b;
    input [4:0] s;
    (* full_case = 32'd1 *)
    (* src = "../../cfg_regs.sv:159.21-159.56|../../cfg_regs.sv:141.13-180.20" *)
    (* parallel_case *)
    casez (s)
      5'b????1:
        _433_ = b[1:0];
      5'b???1?:
        _433_ = b[3:2];
      5'b??1??:
        _433_ = b[5:4];
      5'b?1???:
        _433_ = b[7:6];
      5'b1????:
        _433_ = b[9:8];
      default:
        _433_ = a;
    endcase
  endfunction
  assign _221_ = _433_(_219_, 10'hxxx, { _226_, _225_, _224_, _223_, _222_ });
  assign _222_ = cfg_addr == (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:159.21-159.56|../../cfg_regs.sv:141.13-180.20" *) 8'hc0;
  assign _223_ = cfg_addr == (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:155.21-155.54|../../cfg_regs.sv:141.13-180.20" *) 8'h0c;
  assign _224_ = cfg_addr == (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:151.21-151.55|../../cfg_regs.sv:141.13-180.20" *) 8'h08;
  assign _225_ = cfg_addr == (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:147.21-147.49|../../cfg_regs.sv:141.13-180.20" *) 8'h04;
  assign _226_ = ! (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:143.21-143.55|../../cfg_regs.sv:141.13-180.20" *) cfg_addr;
  assign _228_ = _229_ ? (* src = "../../cfg_regs.sv:137.30-181.12|../../cfg_regs.sv:137.18-181.12" *) _221_ : 2'hx;
  assign _230_ = _231_ ? (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:165.67-170.24|../../cfg_regs.sv:164.21-178.24" *) _076_[15:2] : 14'h0000;
  function [13:0] _441_;
    input [13:0] a;
    input [69:0] b;
    input [4:0] s;
    (* full_case = 32'd1 *)
    (* src = "../../cfg_regs.sv:159.21-159.56|../../cfg_regs.sv:141.13-180.20" *)
    (* parallel_case *)
    casez (s)
      5'b????1:
        _441_ = b[13:0];
      5'b???1?:
        _441_ = b[27:14];
      5'b??1??:
        _441_ = b[41:28];
      5'b?1???:
        _441_ = b[55:42];
      5'b1????:
        _441_ = b[69:56];
      default:
        _441_ = a;
    endcase
  endfunction
  assign _232_ = _441_(_230_, 70'hxxxxxxxxxxxxxxxxxx, { _237_, _236_, _235_, _234_, _233_ });
  assign _233_ = cfg_addr == (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:159.21-159.56|../../cfg_regs.sv:141.13-180.20" *) 8'hc0;
  assign _234_ = cfg_addr == (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:155.21-155.54|../../cfg_regs.sv:141.13-180.20" *) 8'h0c;
  assign _235_ = cfg_addr == (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:151.21-151.55|../../cfg_regs.sv:141.13-180.20" *) 8'h08;
  assign _236_ = cfg_addr == (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:147.21-147.49|../../cfg_regs.sv:141.13-180.20" *) 8'h04;
  assign _237_ = ! (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:143.21-143.55|../../cfg_regs.sv:141.13-180.20" *) cfg_addr;
  assign _238_ = _239_ ? (* src = "../../cfg_regs.sv:137.30-181.12|../../cfg_regs.sv:137.18-181.12" *) _232_ : 14'hxxxx;
  assign _240_ = _241_ ? (* src = "../../cfg_regs.sv:168.29-168.71|../../cfg_regs.sv:167.25-169.28" *) _022_ : 16'h0000;
  assign _242_ = _243_ ? (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:165.67-170.24|../../cfg_regs.sv:164.21-178.24" *) _240_ : 16'hxxxx;
  assign _252_ = _260_ ? (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:210.21-210.47|../../cfg_regs.sv:209.17-213.20" *) 1'h1 : _095_;
  function [15:0] _451_;
    input [15:0] a;
    input [79:0] b;
    input [4:0] s;
    (* full_case = 32'd1 *)
    (* src = "../../cfg_regs.sv:159.21-159.56|../../cfg_regs.sv:141.13-180.20" *)
    (* parallel_case *)
    casez (s)
      5'b????1:
        _451_ = b[15:0];
      5'b???1?:
        _451_ = b[31:16];
      5'b??1??:
        _451_ = b[47:32];
      5'b?1???:
        _451_ = b[63:48];
      5'b1????:
        _451_ = b[79:64];
      default:
        _451_ = a;
    endcase
  endfunction
  assign _244_ = _451_(_242_, 80'hxxxxxxxxxxxxxxxxxxxx, { _249_, _248_, _247_, _246_, _245_ });
  assign _245_ = cfg_addr == (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:159.21-159.56|../../cfg_regs.sv:141.13-180.20" *) 8'hc0;
  assign _246_ = cfg_addr == (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:155.21-155.54|../../cfg_regs.sv:141.13-180.20" *) 8'h0c;
  assign _247_ = cfg_addr == (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:151.21-151.55|../../cfg_regs.sv:141.13-180.20" *) 8'h08;
  assign _248_ = cfg_addr == (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:147.21-147.49|../../cfg_regs.sv:141.13-180.20" *) 8'h04;
  assign _249_ = ! (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:143.21-143.55|../../cfg_regs.sv:141.13-180.20" *) cfg_addr;
  assign _250_ = _251_ ? (* src = "../../cfg_regs.sv:137.30-181.12|../../cfg_regs.sv:137.18-181.12" *) _244_ : 16'hxxxx;
  assign _253_ = _254_ ? (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:165.67-170.24|../../cfg_regs.sv:164.21-178.24" *) _076_[1:0] : _080_;
  function [1:0] _459_;
    input [1:0] a;
    input [9:0] b;
    input [4:0] s;
    (* full_case = 32'd1 *)
    (* src = "../../cfg_regs.sv:159.21-159.56|../../cfg_regs.sv:141.13-180.20" *)
    (* parallel_case *)
    casez (s)
      5'b????1:
        _459_ = b[1:0];
      5'b???1?:
        _459_ = b[3:2];
      5'b??1??:
        _459_ = b[5:4];
      5'b?1???:
        _459_ = b[7:6];
      5'b1????:
        _459_ = b[9:8];
      default:
        _459_ = a;
    endcase
  endfunction
  assign _255_ = _459_(_253_, 10'hxxx, { _099_, _259_, _258_, _257_, _256_ });
  assign _256_ = cfg_addr == (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:159.21-159.56|../../cfg_regs.sv:141.13-180.20" *) 8'hc0;
  assign _257_ = cfg_addr == (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:155.21-155.54|../../cfg_regs.sv:141.13-180.20" *) 8'h0c;
  assign _258_ = cfg_addr == (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:151.21-151.55|../../cfg_regs.sv:141.13-180.20" *) 8'h08;
  assign _259_ = cfg_addr == (* full_case = 32'd1 *) (* src = "../../cfg_regs.sv:147.21-147.49|../../cfg_regs.sv:141.13-180.20" *) 8'h04;
  assign state_changed = { _040_, _039_, _038_, _037_ };
  assign irq = _059_;
  assign periph_en = periph_en_reg;
  assign idle_base_th = idle_base_th_reg;
  assign alpha = alpha_reg;
  assign wake_mask = wake_mask_reg;
  assign _203_ = _056_;
  assign _227_ = state_changed[3];
  assign _095_ = _218_;
  assign _260_ = state_changed[3];
  assign _096_ = _252_;
  assign _117_ = _053_;
  assign _144_ = state_changed[2];
  assign _093_ = _135_;
  assign _174_ = state_changed[2];
  assign _094_ = _165_;
  assign _189_ = _049_;
  assign _198_ = state_changed[1];
  assign _091_ = _197_;
  assign _200_ = state_changed[1];
  assign _092_ = _199_;
  assign _202_ = _046_;
  assign _205_ = state_changed[0];
  assign _089_ = _204_;
  assign _207_ = state_changed[0];
  assign _090_ = _206_;
  assign _215_ = cfg_re;
  assign _078_[15:4] = _214_;
  assign _217_ = _025_;
  assign _220_ = _014_;
  assign _229_ = cfg_re;
  assign _080_ = _228_;
  assign _231_ = _014_;
  assign _239_ = cfg_re;
  assign _077_[15:2] = _238_;
  assign _241_ = _018_;
  assign _243_ = _014_;
  assign _251_ = cfg_re;
  assign _076_ = _250_;
  assign _254_ = _014_;
  assign _101_ = cfg_re;
  assign _077_[1:0] = _100_;
  assign _103_ = _029_;
  assign _105_ = _025_;
  assign _107_ = _014_;
  assign _116_ = cfg_re;
  assign _079_ = _115_;
  assign _125_ = cfg_re;
  assign _078_[3:0] = _124_;
  assign _127_ = cfg_re;
  assign _075_ = _126_;
  assign _129_ = _000_;
  assign _131_ = _050_;
  assign _140_ = cfg_we;
  assign _081_ = _139_;
  assign _142_ = _050_;
  assign _151_ = cfg_we;
  assign _082_ = _150_;
  assign _155_ = cfg_we;
  assign _087_ = _154_;
  assign _159_ = cfg_we;
  assign _085_ = _158_;
  assign _163_ = cfg_we;
  assign _261_ = _162_;
  assign _168_ = cfg_we;
  assign _061_ = _167_;
  assign _177_ = cfg_we;
  assign _083_ = _176_;
  assign _183_ = cfg_we;
  assign _097_ = _182_;
  assign _185_ = cfg_we;
  assign _088_ = _184_;
  assign _187_ = cfg_we;
  assign _086_ = _186_;
  assign _190_ = cfg_we;
  assign _262_ = _188_;
  assign _192_ = cfg_we;
  assign _062_ = _191_;
  assign _194_ = cfg_we;
  assign _084_ = _193_;
  assign _196_ = cfg_we;
  assign _098_ = _195_;
  assign _009_ = rst_n;
  assign _060_ = { 2'h0, _057_[31:2] };
  assign _011_ = rst_n;
  assign _016_ = { 2'h0, _015_[31:2] };
  assign _028_ = { 2'h0, _026_[31:2] };
  assign _036_ = rst_n;
  assign _043_ = rst_n;
  assign _022_ = _021_;
  assign _033_ = _032_;
  assign _031_ = _064_;
  assign _020_ = _066_;
endmodule
