/* Generated by Yosys 0.53 (git sha1 53c22ab7c, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "../../cfg_regs.sv:8.8" *)
module cfg_regs(clk, rst_n, cfg_addr, cfg_wdata, cfg_we, cfg_re, cfg_rdata, state, periph_en, idle_base_th, alpha, wake_mask, irq);
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire _365_;
  wire _366_;
  wire _367_;
  wire _368_;
  wire _369_;
  wire _370_;
  wire _371_;
  wire _372_;
  wire _373_;
  wire _374_;
  wire _375_;
  wire _376_;
  wire _377_;
  wire _378_;
  wire _379_;
  wire _380_;
  wire _381_;
  wire _382_;
  wire _383_;
  wire _384_;
  wire _385_;
  wire _386_;
  wire _387_;
  wire _388_;
  wire _389_;
  wire _390_;
  wire _391_;
  wire _392_;
  wire _393_;
  wire _394_;
  wire _395_;
  wire _396_;
  wire _397_;
  wire _398_;
  wire _399_;
  wire _400_;
  wire _401_;
  wire _402_;
  wire _403_;
  wire _404_;
  wire _405_;
  wire _406_;
  wire _407_;
  wire _408_;
  wire _409_;
  wire _410_;
  wire _411_;
  wire _412_;
  wire _413_;
  wire _414_;
  wire _415_;
  wire _416_;
  wire _417_;
  wire _418_;
  wire _419_;
  wire _420_;
  wire _421_;
  wire _422_;
  wire _423_;
  wire _424_;
  wire _425_;
  wire _426_;
  wire _427_;
  wire _428_;
  wire _429_;
  wire _430_;
  wire _431_;
  wire _432_;
  (* src = "/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:33.14-33.19" *)
  wire [3:0] _027_;
  (* src = "../../cfg_regs.sv:209.17-213.20" *)
  wire _090_;
  (* src = "../../cfg_regs.sv:209.17-213.20" *)
  wire _092_;
  (* src = "../../cfg_regs.sv:209.17-213.20" *)
  wire _094_;
  (* src = "../../cfg_regs.sv:209.17-213.20" *)
  wire _096_;
  (* src = "/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:150.14-150.19" *)
  wire [3:0] _118_;
  (* src = "/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:240.15-240.20" *)
  wire [11:0] _208_;
  (* nosync = 32'd1 *)
  (* src = "/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:498.17-498.18" *)
  wire [1:0] \_355_$func$/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:519$11.a ;
  (* nosync = 32'd1 *)
  (* src = "/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:500.17-500.18" *)
  wire [4:0] \_355_$func$/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:519$11.s ;
  (* nosync = 32'd1 *)
  (* src = "/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:527.17-527.18" *)
  wire [3:0] \_362_$func$/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:548$12.a ;
  (* nosync = 32'd1 *)
  (* src = "/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:528.18-528.19" *)
  wire [19:0] \_362_$func$/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:548$12.b ;
  (* nosync = 32'd1 *)
  (* src = "/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:529.17-529.18" *)
  wire [4:0] \_362_$func$/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:548$12.s ;
  (* nosync = 32'd1 *)
  (* src = "/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:560.18-560.19" *)
  wire [63:0] \_373_$func$/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:581$13.a ;
  (* nosync = 32'd1 *)
  (* src = "/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:562.17-562.18" *)
  wire [4:0] \_373_$func$/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:581$13.s ;
  (* nosync = 32'd1 *)
  (* src = "/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:590.18-590.19" *)
  wire [63:0] \_381_$func$/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:611$14.a ;
  (* nosync = 32'd1 *)
  (* src = "/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:592.17-592.18" *)
  wire [4:0] \_381_$func$/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:611$14.s ;
  (* nosync = 32'd1 *)
  (* src = "/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:632.18-632.19" *)
  wire [63:0] \_401_$func$/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:653$15.a ;
  (* nosync = 32'd1 *)
  (* src = "/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:633.19-633.20" *)
  wire [319:0] \_401_$func$/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:653$15.b ;
  (* nosync = 32'd1 *)
  (* src = "/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:634.17-634.18" *)
  wire [4:0] \_401_$func$/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:653$15.s ;
  (* nosync = 32'd1 *)
  (* src = "/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:676.18-676.19" *)
  wire [11:0] \_423_$func$/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:697$16.a ;
  (* nosync = 32'd1 *)
  (* src = "/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:678.17-678.18" *)
  wire [4:0] \_423_$func$/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:697$16.s ;
  (* nosync = 32'd1 *)
  (* src = "/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:708.17-708.18" *)
  wire [1:0] \_433_$func$/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:729$17.a ;
  (* nosync = 32'd1 *)
  (* src = "/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:710.17-710.18" *)
  wire [4:0] \_433_$func$/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:729$17.s ;
  (* nosync = 32'd1 *)
  (* src = "/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:738.18-738.19" *)
  wire [13:0] \_441_$func$/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:759$18.a ;
  (* nosync = 32'd1 *)
  (* src = "/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:740.17-740.18" *)
  wire [4:0] \_441_$func$/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:759$18.s ;
  (* nosync = 32'd1 *)
  (* src = "/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:770.18-770.19" *)
  wire [15:0] \_451_$func$/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:791$19.a ;
  (* nosync = 32'd1 *)
  (* src = "/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:772.17-772.18" *)
  wire [4:0] \_451_$func$/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:791$19.s ;
  (* nosync = 32'd1 *)
  (* src = "/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:800.17-800.18" *)
  wire [1:0] \_459_$func$/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:821$20.a ;
  (* nosync = 32'd1 *)
  (* src = "/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:802.17-802.18" *)
  wire [4:0] \_459_$func$/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:821$20.s ;
  (* src = "../../cfg_regs.sv:31.37" *)
  output [3:0] alpha;
  wire [3:0] alpha;
  (* src = "../../cfg_regs.sv:68.30" *)
  reg [3:0] alpha_reg;
  (* src = "../../cfg_regs.sv:19.37" *)
  input [7:0] cfg_addr;
  wire [7:0] cfg_addr;
  (* src = "../../cfg_regs.sv:23.37" *)
  output [31:0] cfg_rdata;
  wire [31:0] cfg_rdata;
  (* src = "../../cfg_regs.sv:22.37" *)
  input cfg_re;
  wire cfg_re;
  (* src = "../../cfg_regs.sv:20.37" *)
  input [31:0] cfg_wdata;
  wire [31:0] cfg_wdata;
  (* src = "../../cfg_regs.sv:21.37" *)
  input cfg_we;
  wire cfg_we;
  (* src = "../../cfg_regs.sv:15.37" *)
  input clk;
  wire clk;
  (* src = "../../cfg_regs.sv:30.37" *)
  output [63:0] idle_base_th;
  wire [63:0] idle_base_th;
  (* src = "../../cfg_regs.sv:67.30" *)
  reg [63:0] idle_base_th_reg;
  (* src = "../../cfg_regs.sv:35.37" *)
  output irq;
  wire irq;
  (* src = "../../cfg_regs.sv:70.30" *)
  reg [3:0] irq_mask_reg;
  (* src = "../../cfg_regs.sv:71.30" *)
  reg [3:0] irq_status_reg;
  (* src = "../../cfg_regs.sv:29.37" *)
  output [3:0] periph_en;
  wire [3:0] periph_en;
  (* src = "../../cfg_regs.sv:66.30" *)
  reg [3:0] periph_en_reg;
  (* src = "../../cfg_regs.sv:16.37" *)
  input rst_n;
  wire rst_n;
  (* src = "../../cfg_regs.sv:26.37" *)
  input [7:0] state;
  wire [7:0] state;
  (* src = "../../cfg_regs.sv:75.30" *)
  wire [3:0] state_changed;
  (* src = "../../cfg_regs.sv:74.30" *)
  reg [7:0] state_prev;
  (* src = "../../cfg_regs.sv:32.37" *)
  output [3:0] wake_mask;
  wire [3:0] wake_mask;
  (* src = "../../cfg_regs.sv:69.30" *)
  reg [3:0] wake_mask_reg;
  assign _221_ = ~(cfg_addr[3] & cfg_addr[2]);
  assign _222_ = ~(cfg_addr[7] | cfg_addr[6]);
  assign _223_ = cfg_addr[7] | cfg_addr[6];
  assign _224_ = ~(cfg_addr[4] | cfg_addr[5]);
  assign _225_ = ~(_224_ | _223_);
  assign _226_ = _222_ & ~(_225_);
  assign _227_ = ~cfg_addr[7];
  assign _228_ = _224_ & ~(cfg_addr[6]);
  assign _229_ = _228_ ^ _227_;
  assign _230_ = _224_ ^ cfg_addr[6];
  assign _231_ = _230_ | ~(_229_);
  assign _232_ = _229_ & ~(_230_);
  assign _233_ = cfg_addr[4] & ~(cfg_addr[5]);
  assign _234_ = _232_ & ~(_233_);
  assign _235_ = _234_ | _231_;
  assign _236_ = _235_ | _226_;
  assign _237_ = ~(_236_ | _221_);
  assign _238_ = cfg_addr[1] | cfg_addr[0];
  assign _239_ = cfg_addr[3] | cfg_addr[2];
  assign _240_ = ~(_239_ | _238_);
  assign _241_ = cfg_addr[4] | cfg_addr[5];
  assign _242_ = cfg_addr[7] & cfg_addr[6];
  assign _243_ = _241_ | ~(_242_);
  assign _244_ = _243_ | ~(_240_);
  assign _245_ = _241_ | _223_;
  assign _246_ = _245_ | ~(_240_);
  assign _247_ = ~(_246_ & _244_);
  assign _248_ = _238_ | _221_;
  assign _249_ = _248_ | _245_;
  assign _250_ = cfg_addr[2] | ~(cfg_addr[3]);
  assign _251_ = _250_ | _238_;
  assign _252_ = _251_ | _245_;
  assign _253_ = ~(_252_ & _249_);
  assign _254_ = _253_ | _247_;
  assign _255_ = cfg_addr[3] | ~(cfg_addr[2]);
  assign _256_ = _255_ | _238_;
  assign _257_ = _256_ | _245_;
  assign _258_ = _257_ & ~(_254_);
  assign _259_ = _258_ & ~(_236_);
  assign _260_ = ~cfg_we;
  assign _261_ = cfg_addr[5] | ~(cfg_addr[4]);
  assign _262_ = _261_ | _223_;
  assign _263_ = _240_ & ~(_262_);
  assign _264_ = _226_ & ~(_263_);
  assign _265_ = cfg_addr[5] | cfg_addr[6];
  assign _266_ = _265_ | cfg_addr[7];
  assign _267_ = _266_ | _264_;
  assign _268_ = _267_ | _260_;
  assign _269_ = _259_ & ~(_268_);
  assign _213_ = _269_ & _237_;
  assign _270_ = _250_ | _236_;
  assign _214_ = _269_ & ~(_270_);
  assign _271_ = _255_ | _236_;
  assign _215_ = _269_ & ~(_271_);
  assign _272_ = _239_ | _236_;
  assign _216_ = _269_ & ~(_272_);
  assign _217_ = cfg_we & ~(_257_);
  assign _218_ = cfg_we & ~(_249_);
  assign _273_ = _244_ | _260_;
  assign _274_ = state_prev[4] ^ state[4];
  assign _275_ = state_prev[5] ^ state[5];
  assign _094_ = _275_ | _274_;
  assign _276_ = cfg_wdata[2] & ~(_273_);
  assign _209_ = _276_ | _094_;
  assign _277_ = state_prev[2] ^ state[2];
  assign _278_ = state_prev[3] ^ state[3];
  assign _092_ = _278_ | _277_;
  assign _279_ = cfg_wdata[1] & ~(_273_);
  assign _210_ = _279_ | _092_;
  assign _280_ = state_prev[0] ^ state[0];
  assign _281_ = state_prev[1] ^ state[1];
  assign _090_ = _281_ | _280_;
  assign _282_ = cfg_wdata[0] & ~(_273_);
  assign _211_ = _282_ | _090_;
  assign _283_ = state_prev[6] ^ state[6];
  assign _284_ = state_prev[7] ^ state[7];
  assign _096_ = _284_ | _283_;
  assign _285_ = cfg_wdata[3] & ~(_273_);
  assign _212_ = _285_ | _096_;
  assign _219_ = cfg_we & ~(_246_);
  assign _220_ = cfg_we & ~(_252_);
  assign _286_ = irq_mask_reg[0] & irq_status_reg[0];
  assign _287_ = irq_mask_reg[1] & irq_status_reg[1];
  assign _288_ = _287_ | _286_;
  assign _289_ = irq_mask_reg[2] & irq_status_reg[2];
  assign _290_ = irq_mask_reg[3] & irq_status_reg[3];
  assign _291_ = _290_ | _289_;
  assign irq = _291_ | _288_;
  assign _292_ = cfg_addr[2] ? idle_base_th_reg[20] : idle_base_th_reg[4];
  assign _293_ = cfg_addr[2] ? idle_base_th_reg[52] : idle_base_th_reg[36];
  assign _294_ = cfg_addr[3] ? _293_ : _292_;
  assign _295_ = _236_ | ~(_294_);
  assign _296_ = _295_ | _267_;
  assign _208_[0] = _258_ & ~(_296_);
  assign _297_ = cfg_addr[2] ? idle_base_th_reg[21] : idle_base_th_reg[5];
  assign _298_ = cfg_addr[2] ? idle_base_th_reg[53] : idle_base_th_reg[37];
  assign _299_ = cfg_addr[3] ? _298_ : _297_;
  assign _300_ = _236_ | ~(_299_);
  assign _301_ = _300_ | _267_;
  assign _208_[1] = _258_ & ~(_301_);
  assign _302_ = cfg_addr[2] ? idle_base_th_reg[22] : idle_base_th_reg[6];
  assign _303_ = cfg_addr[2] ? idle_base_th_reg[54] : idle_base_th_reg[38];
  assign _304_ = cfg_addr[3] ? _303_ : _302_;
  assign _305_ = _236_ | ~(_304_);
  assign _306_ = _305_ | _267_;
  assign _208_[2] = _258_ & ~(_306_);
  assign _307_ = cfg_addr[2] ? idle_base_th_reg[23] : idle_base_th_reg[7];
  assign _308_ = cfg_addr[2] ? idle_base_th_reg[55] : idle_base_th_reg[39];
  assign _309_ = cfg_addr[3] ? _308_ : _307_;
  assign _310_ = _236_ | ~(_309_);
  assign _311_ = _310_ | _267_;
  assign _208_[3] = _258_ & ~(_311_);
  assign _312_ = cfg_addr[2] ? idle_base_th_reg[24] : idle_base_th_reg[8];
  assign _313_ = cfg_addr[2] ? idle_base_th_reg[56] : idle_base_th_reg[40];
  assign _314_ = cfg_addr[3] ? _313_ : _312_;
  assign _315_ = _236_ | ~(_314_);
  assign _316_ = _315_ | _267_;
  assign _208_[4] = _258_ & ~(_316_);
  assign _317_ = cfg_addr[2] ? idle_base_th_reg[25] : idle_base_th_reg[9];
  assign _318_ = cfg_addr[2] ? idle_base_th_reg[57] : idle_base_th_reg[41];
  assign _319_ = cfg_addr[3] ? _318_ : _317_;
  assign _320_ = _236_ | ~(_319_);
  assign _321_ = _320_ | _267_;
  assign _208_[5] = _258_ & ~(_321_);
  assign _322_ = cfg_addr[2] ? idle_base_th_reg[26] : idle_base_th_reg[10];
  assign _323_ = cfg_addr[2] ? idle_base_th_reg[58] : idle_base_th_reg[42];
  assign _324_ = cfg_addr[3] ? _323_ : _322_;
  assign _325_ = _236_ | ~(_324_);
  assign _326_ = _325_ | _267_;
  assign _208_[6] = _258_ & ~(_326_);
  assign _327_ = cfg_addr[2] ? idle_base_th_reg[27] : idle_base_th_reg[11];
  assign _328_ = cfg_addr[2] ? idle_base_th_reg[59] : idle_base_th_reg[43];
  assign _329_ = cfg_addr[3] ? _328_ : _327_;
  assign _330_ = _236_ | ~(_329_);
  assign _331_ = _330_ | _267_;
  assign _208_[7] = _258_ & ~(_331_);
  assign _332_ = cfg_addr[2] ? idle_base_th_reg[28] : idle_base_th_reg[12];
  assign _333_ = cfg_addr[2] ? idle_base_th_reg[60] : idle_base_th_reg[44];
  assign _334_ = cfg_addr[3] ? _333_ : _332_;
  assign _335_ = _236_ | ~(_334_);
  assign _336_ = _335_ | _267_;
  assign _208_[8] = _258_ & ~(_336_);
  assign _337_ = cfg_addr[2] ? idle_base_th_reg[29] : idle_base_th_reg[13];
  assign _338_ = cfg_addr[2] ? idle_base_th_reg[61] : idle_base_th_reg[45];
  assign _339_ = cfg_addr[3] ? _338_ : _337_;
  assign _340_ = _236_ | ~(_339_);
  assign _341_ = _340_ | _267_;
  assign _208_[9] = _258_ & ~(_341_);
  assign _342_ = cfg_addr[2] ? idle_base_th_reg[30] : idle_base_th_reg[14];
  assign _343_ = cfg_addr[2] ? idle_base_th_reg[62] : idle_base_th_reg[46];
  assign _344_ = cfg_addr[3] ? _343_ : _342_;
  assign _345_ = _236_ | ~(_344_);
  assign _346_ = _345_ | _267_;
  assign _208_[10] = _258_ & ~(_346_);
  assign _347_ = cfg_addr[2] ? idle_base_th_reg[31] : idle_base_th_reg[15];
  assign _348_ = cfg_addr[2] ? idle_base_th_reg[63] : idle_base_th_reg[47];
  assign _349_ = cfg_addr[3] ? _348_ : _347_;
  assign _350_ = _236_ | ~(_349_);
  assign _351_ = _350_ | _267_;
  assign _208_[11] = _258_ & ~(_351_);
  assign _352_ = cfg_addr[2] ? state[2] : state[0];
  assign _353_ = cfg_addr[2] ? state[6] : state[4];
  assign _354_ = cfg_addr[3] ? _353_ : _352_;
  assign _355_ = cfg_addr[6] | ~(cfg_addr[7]);
  assign _356_ = ~(_355_ | _224_);
  assign _357_ = _356_ | _355_;
  assign _358_ = _357_ | _227_;
  assign _359_ = _358_ | ~(_354_);
  assign _360_ = ~(cfg_addr[4] | cfg_addr[2]);
  assign _361_ = _360_ & ~(_238_);
  assign _362_ = cfg_addr[5] | cfg_addr[3];
  assign _363_ = _362_ | _355_;
  assign _364_ = _361_ & ~(_363_);
  assign _365_ = _364_ | cfg_addr[7];
  assign _366_ = _356_ | _242_;
  assign _367_ = _365_ & ~(_366_);
  assign _368_ = _367_ & ~(_359_);
  assign _369_ = cfg_addr[2] ? idle_base_th_reg[16] : idle_base_th_reg[0];
  assign _370_ = cfg_addr[2] ? idle_base_th_reg[48] : idle_base_th_reg[32];
  assign _371_ = cfg_addr[3] ? _370_ : _369_;
  assign _372_ = _371_ & ~(_236_);
  assign _373_ = _267_ ? _368_ : _372_;
  assign _374_ = ~(_257_ & _246_);
  assign _375_ = _374_ | _253_;
  assign _376_ = _244_ & ~(_375_);
  assign _377_ = periph_en_reg[0] & ~(_246_);
  assign _378_ = alpha_reg[0] & ~(_257_);
  assign _379_ = _378_ | _377_;
  assign _380_ = wake_mask_reg[0] & ~(_252_);
  assign _381_ = irq_mask_reg[0] & ~(_249_);
  assign _382_ = _381_ | _380_;
  assign _383_ = _382_ | _379_;
  assign _384_ = irq_status_reg[0] & ~(_244_);
  assign _385_ = _384_ | _383_;
  assign _118_[0] = _376_ ? _373_ : _385_;
  assign _386_ = cfg_addr[2] ? state[3] : state[1];
  assign _387_ = cfg_addr[2] ? state[7] : state[5];
  assign _388_ = cfg_addr[3] ? _387_ : _386_;
  assign _389_ = _358_ | ~(_388_);
  assign _390_ = _367_ & ~(_389_);
  assign _391_ = cfg_addr[2] ? idle_base_th_reg[17] : idle_base_th_reg[1];
  assign _392_ = cfg_addr[2] ? idle_base_th_reg[49] : idle_base_th_reg[33];
  assign _393_ = cfg_addr[3] ? _392_ : _391_;
  assign _394_ = _393_ & ~(_236_);
  assign _395_ = _267_ ? _390_ : _394_;
  assign _396_ = periph_en_reg[1] & ~(_246_);
  assign _397_ = alpha_reg[1] & ~(_257_);
  assign _398_ = _397_ | _396_;
  assign _399_ = wake_mask_reg[1] & ~(_252_);
  assign _400_ = irq_mask_reg[1] & ~(_249_);
  assign _401_ = _400_ | _399_;
  assign _402_ = _401_ | _398_;
  assign _403_ = irq_status_reg[1] & ~(_244_);
  assign _404_ = _403_ | _402_;
  assign _118_[1] = _376_ ? _395_ : _404_;
  assign _405_ = cfg_addr[2] ? idle_base_th_reg[18] : idle_base_th_reg[2];
  assign _406_ = cfg_addr[2] ? idle_base_th_reg[50] : idle_base_th_reg[34];
  assign _407_ = cfg_addr[3] ? _406_ : _405_;
  assign _408_ = _236_ | ~(_407_);
  assign _409_ = ~(_408_ | _267_);
  assign _410_ = periph_en_reg[2] & ~(_246_);
  assign _411_ = alpha_reg[2] & ~(_257_);
  assign _412_ = _411_ | _410_;
  assign _413_ = wake_mask_reg[2] & ~(_252_);
  assign _414_ = irq_mask_reg[2] & ~(_249_);
  assign _415_ = _414_ | _413_;
  assign _416_ = _415_ | _412_;
  assign _417_ = irq_status_reg[2] & ~(_244_);
  assign _418_ = _417_ | _416_;
  assign _118_[2] = _376_ ? _409_ : _418_;
  assign _419_ = cfg_addr[2] ? idle_base_th_reg[19] : idle_base_th_reg[3];
  assign _420_ = cfg_addr[2] ? idle_base_th_reg[51] : idle_base_th_reg[35];
  assign _421_ = cfg_addr[3] ? _420_ : _419_;
  assign _422_ = _236_ | ~(_421_);
  assign _423_ = ~(_422_ | _267_);
  assign _424_ = periph_en_reg[3] & ~(_246_);
  assign _425_ = alpha_reg[3] & ~(_257_);
  assign _426_ = _425_ | _424_;
  assign _427_ = wake_mask_reg[3] & ~(_252_);
  assign _428_ = irq_mask_reg[3] & ~(_249_);
  assign _429_ = _428_ | _427_;
  assign _430_ = _429_ | _426_;
  assign _431_ = irq_status_reg[3] & ~(_244_);
  assign _432_ = _431_ | _430_;
  assign _118_[3] = _376_ ? _423_ : _432_;
  assign _027_[0] = irq_status_reg[0] & ~(cfg_wdata[0]);
  assign _027_[1] = irq_status_reg[1] & ~(cfg_wdata[1]);
  assign _027_[2] = irq_status_reg[2] & ~(cfg_wdata[2]);
  assign _027_[3] = irq_status_reg[3] & ~(cfg_wdata[3]);
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) alpha_reg[0] <= 1'h0;
    else if (_217_) alpha_reg[0] <= cfg_wdata[0];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) alpha_reg[1] <= 1'h0;
    else if (_217_) alpha_reg[1] <= cfg_wdata[1];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) alpha_reg[2] <= 1'h0;
    else if (_217_) alpha_reg[2] <= cfg_wdata[2];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) alpha_reg[3] <= 1'h1;
    else if (_217_) alpha_reg[3] <= cfg_wdata[3];
  reg \cfg_rdata_reg[0] ;
  (* src = "../../cfg_regs.sv:134.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \cfg_rdata_reg[0]  <= 1'h0;
    else if (cfg_re) \cfg_rdata_reg[0]  <= _118_[0];
  assign cfg_rdata[0] = \cfg_rdata_reg[0] ;
  reg \cfg_rdata_reg[1] ;
  (* src = "../../cfg_regs.sv:134.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \cfg_rdata_reg[1]  <= 1'h0;
    else if (cfg_re) \cfg_rdata_reg[1]  <= _118_[1];
  assign cfg_rdata[1] = \cfg_rdata_reg[1] ;
  reg \cfg_rdata_reg[2] ;
  (* src = "../../cfg_regs.sv:134.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \cfg_rdata_reg[2]  <= 1'h0;
    else if (cfg_re) \cfg_rdata_reg[2]  <= _118_[2];
  assign cfg_rdata[2] = \cfg_rdata_reg[2] ;
  reg \cfg_rdata_reg[3] ;
  (* src = "../../cfg_regs.sv:134.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \cfg_rdata_reg[3]  <= 1'h0;
    else if (cfg_re) \cfg_rdata_reg[3]  <= _118_[3];
  assign cfg_rdata[3] = \cfg_rdata_reg[3] ;
  reg \cfg_rdata_reg[4] ;
  (* src = "../../cfg_regs.sv:134.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \cfg_rdata_reg[4]  <= 1'h0;
    else if (cfg_re) \cfg_rdata_reg[4]  <= _208_[0];
  assign cfg_rdata[4] = \cfg_rdata_reg[4] ;
  reg \cfg_rdata_reg[5] ;
  (* src = "../../cfg_regs.sv:134.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \cfg_rdata_reg[5]  <= 1'h0;
    else if (cfg_re) \cfg_rdata_reg[5]  <= _208_[1];
  assign cfg_rdata[5] = \cfg_rdata_reg[5] ;
  reg \cfg_rdata_reg[6] ;
  (* src = "../../cfg_regs.sv:134.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \cfg_rdata_reg[6]  <= 1'h0;
    else if (cfg_re) \cfg_rdata_reg[6]  <= _208_[2];
  assign cfg_rdata[6] = \cfg_rdata_reg[6] ;
  reg \cfg_rdata_reg[7] ;
  (* src = "../../cfg_regs.sv:134.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \cfg_rdata_reg[7]  <= 1'h0;
    else if (cfg_re) \cfg_rdata_reg[7]  <= _208_[3];
  assign cfg_rdata[7] = \cfg_rdata_reg[7] ;
  reg \cfg_rdata_reg[8] ;
  (* src = "../../cfg_regs.sv:134.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \cfg_rdata_reg[8]  <= 1'h0;
    else if (cfg_re) \cfg_rdata_reg[8]  <= _208_[4];
  assign cfg_rdata[8] = \cfg_rdata_reg[8] ;
  reg \cfg_rdata_reg[9] ;
  (* src = "../../cfg_regs.sv:134.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \cfg_rdata_reg[9]  <= 1'h0;
    else if (cfg_re) \cfg_rdata_reg[9]  <= _208_[5];
  assign cfg_rdata[9] = \cfg_rdata_reg[9] ;
  reg \cfg_rdata_reg[10] ;
  (* src = "../../cfg_regs.sv:134.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \cfg_rdata_reg[10]  <= 1'h0;
    else if (cfg_re) \cfg_rdata_reg[10]  <= _208_[6];
  assign cfg_rdata[10] = \cfg_rdata_reg[10] ;
  reg \cfg_rdata_reg[11] ;
  (* src = "../../cfg_regs.sv:134.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \cfg_rdata_reg[11]  <= 1'h0;
    else if (cfg_re) \cfg_rdata_reg[11]  <= _208_[7];
  assign cfg_rdata[11] = \cfg_rdata_reg[11] ;
  reg \cfg_rdata_reg[12] ;
  (* src = "../../cfg_regs.sv:134.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \cfg_rdata_reg[12]  <= 1'h0;
    else if (cfg_re) \cfg_rdata_reg[12]  <= _208_[8];
  assign cfg_rdata[12] = \cfg_rdata_reg[12] ;
  reg \cfg_rdata_reg[13] ;
  (* src = "../../cfg_regs.sv:134.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \cfg_rdata_reg[13]  <= 1'h0;
    else if (cfg_re) \cfg_rdata_reg[13]  <= _208_[9];
  assign cfg_rdata[13] = \cfg_rdata_reg[13] ;
  reg \cfg_rdata_reg[14] ;
  (* src = "../../cfg_regs.sv:134.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \cfg_rdata_reg[14]  <= 1'h0;
    else if (cfg_re) \cfg_rdata_reg[14]  <= _208_[10];
  assign cfg_rdata[14] = \cfg_rdata_reg[14] ;
  reg \cfg_rdata_reg[15] ;
  (* src = "../../cfg_regs.sv:134.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \cfg_rdata_reg[15]  <= 1'h0;
    else if (cfg_re) \cfg_rdata_reg[15]  <= _208_[11];
  assign cfg_rdata[15] = \cfg_rdata_reg[15] ;
  (* src = "../../cfg_regs.sv:187.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_prev[6] <= 1'h0;
    else state_prev[6] <= state[6];
  (* src = "../../cfg_regs.sv:187.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_prev[7] <= 1'h0;
    else state_prev[7] <= state[7];
  (* src = "../../cfg_regs.sv:187.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_prev[4] <= 1'h0;
    else state_prev[4] <= state[4];
  (* src = "../../cfg_regs.sv:187.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_prev[5] <= 1'h0;
    else state_prev[5] <= state[5];
  (* src = "../../cfg_regs.sv:187.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_prev[2] <= 1'h0;
    else state_prev[2] <= state[2];
  (* src = "../../cfg_regs.sv:187.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_prev[3] <= 1'h0;
    else state_prev[3] <= state[3];
  (* src = "../../cfg_regs.sv:187.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_prev[0] <= 1'h0;
    else state_prev[0] <= state[0];
  (* src = "../../cfg_regs.sv:187.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state_prev[1] <= 1'h0;
    else state_prev[1] <= state[1];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) wake_mask_reg[0] <= 1'h1;
    else if (_220_) wake_mask_reg[0] <= cfg_wdata[0];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) wake_mask_reg[1] <= 1'h1;
    else if (_220_) wake_mask_reg[1] <= cfg_wdata[1];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) wake_mask_reg[2] <= 1'h1;
    else if (_220_) wake_mask_reg[2] <= cfg_wdata[2];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) wake_mask_reg[3] <= 1'h1;
    else if (_220_) wake_mask_reg[3] <= cfg_wdata[3];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) periph_en_reg[0] <= 1'h0;
    else if (_219_) periph_en_reg[0] <= cfg_wdata[0];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) periph_en_reg[1] <= 1'h0;
    else if (_219_) periph_en_reg[1] <= cfg_wdata[1];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) periph_en_reg[2] <= 1'h0;
    else if (_219_) periph_en_reg[2] <= cfg_wdata[2];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) periph_en_reg[3] <= 1'h0;
    else if (_219_) periph_en_reg[3] <= cfg_wdata[3];
  (* src = "../../cfg_regs.sv:203.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) irq_status_reg[2] <= 1'h0;
    else if (_209_) irq_status_reg[2] <= _094_;
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) irq_status_reg[0] <= 1'h0;
    else if (!_273_) irq_status_reg[0] <= _027_[0];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) irq_status_reg[1] <= 1'h0;
    else if (!_273_) irq_status_reg[1] <= _027_[1];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) irq_status_reg[2] <= 1'h0;
    else if (!_273_) irq_status_reg[2] <= _027_[2];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) irq_status_reg[3] <= 1'h0;
    else if (!_273_) irq_status_reg[3] <= _027_[3];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) irq_mask_reg[0] <= 1'h0;
    else if (_218_) irq_mask_reg[0] <= cfg_wdata[0];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) irq_mask_reg[1] <= 1'h0;
    else if (_218_) irq_mask_reg[1] <= cfg_wdata[1];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) irq_mask_reg[2] <= 1'h0;
    else if (_218_) irq_mask_reg[2] <= cfg_wdata[2];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) irq_mask_reg[3] <= 1'h0;
    else if (_218_) irq_mask_reg[3] <= cfg_wdata[3];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[63] <= 1'h0;
    else if (_213_) idle_base_th_reg[63] <= cfg_wdata[15];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[47] <= 1'h0;
    else if (_214_) idle_base_th_reg[47] <= cfg_wdata[15];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[31] <= 1'h0;
    else if (_215_) idle_base_th_reg[31] <= cfg_wdata[15];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[15] <= 1'h0;
    else if (_216_) idle_base_th_reg[15] <= cfg_wdata[15];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[11] <= 1'h0;
    else if (_216_) idle_base_th_reg[11] <= cfg_wdata[11];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[12] <= 1'h0;
    else if (_216_) idle_base_th_reg[12] <= cfg_wdata[12];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[13] <= 1'h0;
    else if (_216_) idle_base_th_reg[13] <= cfg_wdata[13];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[7] <= 1'h1;
    else if (_216_) idle_base_th_reg[7] <= cfg_wdata[7];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[14] <= 1'h0;
    else if (_216_) idle_base_th_reg[14] <= cfg_wdata[14];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[8] <= 1'h1;
    else if (_216_) idle_base_th_reg[8] <= cfg_wdata[8];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[9] <= 1'h1;
    else if (_216_) idle_base_th_reg[9] <= cfg_wdata[9];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[6] <= 1'h1;
    else if (_216_) idle_base_th_reg[6] <= cfg_wdata[6];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[10] <= 1'h0;
    else if (_216_) idle_base_th_reg[10] <= cfg_wdata[10];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[48] <= 1'h0;
    else if (_213_) idle_base_th_reg[48] <= cfg_wdata[0];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[49] <= 1'h0;
    else if (_213_) idle_base_th_reg[49] <= cfg_wdata[1];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[50] <= 1'h0;
    else if (_213_) idle_base_th_reg[50] <= cfg_wdata[2];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[51] <= 1'h1;
    else if (_213_) idle_base_th_reg[51] <= cfg_wdata[3];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[52] <= 1'h0;
    else if (_213_) idle_base_th_reg[52] <= cfg_wdata[4];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[53] <= 1'h1;
    else if (_213_) idle_base_th_reg[53] <= cfg_wdata[5];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[54] <= 1'h1;
    else if (_213_) idle_base_th_reg[54] <= cfg_wdata[6];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[55] <= 1'h1;
    else if (_213_) idle_base_th_reg[55] <= cfg_wdata[7];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[56] <= 1'h1;
    else if (_213_) idle_base_th_reg[56] <= cfg_wdata[8];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[57] <= 1'h1;
    else if (_213_) idle_base_th_reg[57] <= cfg_wdata[9];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[58] <= 1'h0;
    else if (_213_) idle_base_th_reg[58] <= cfg_wdata[10];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[59] <= 1'h0;
    else if (_213_) idle_base_th_reg[59] <= cfg_wdata[11];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[60] <= 1'h0;
    else if (_213_) idle_base_th_reg[60] <= cfg_wdata[12];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[61] <= 1'h0;
    else if (_213_) idle_base_th_reg[61] <= cfg_wdata[13];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[62] <= 1'h0;
    else if (_213_) idle_base_th_reg[62] <= cfg_wdata[14];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[32] <= 1'h0;
    else if (_214_) idle_base_th_reg[32] <= cfg_wdata[0];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[33] <= 1'h0;
    else if (_214_) idle_base_th_reg[33] <= cfg_wdata[1];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[34] <= 1'h0;
    else if (_214_) idle_base_th_reg[34] <= cfg_wdata[2];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[35] <= 1'h1;
    else if (_214_) idle_base_th_reg[35] <= cfg_wdata[3];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[36] <= 1'h0;
    else if (_214_) idle_base_th_reg[36] <= cfg_wdata[4];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[37] <= 1'h1;
    else if (_214_) idle_base_th_reg[37] <= cfg_wdata[5];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[38] <= 1'h1;
    else if (_214_) idle_base_th_reg[38] <= cfg_wdata[6];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[39] <= 1'h1;
    else if (_214_) idle_base_th_reg[39] <= cfg_wdata[7];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[40] <= 1'h1;
    else if (_214_) idle_base_th_reg[40] <= cfg_wdata[8];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[41] <= 1'h1;
    else if (_214_) idle_base_th_reg[41] <= cfg_wdata[9];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[42] <= 1'h0;
    else if (_214_) idle_base_th_reg[42] <= cfg_wdata[10];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[43] <= 1'h0;
    else if (_214_) idle_base_th_reg[43] <= cfg_wdata[11];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[44] <= 1'h0;
    else if (_214_) idle_base_th_reg[44] <= cfg_wdata[12];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[45] <= 1'h0;
    else if (_214_) idle_base_th_reg[45] <= cfg_wdata[13];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[46] <= 1'h0;
    else if (_214_) idle_base_th_reg[46] <= cfg_wdata[14];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[16] <= 1'h0;
    else if (_215_) idle_base_th_reg[16] <= cfg_wdata[0];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[17] <= 1'h0;
    else if (_215_) idle_base_th_reg[17] <= cfg_wdata[1];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[18] <= 1'h0;
    else if (_215_) idle_base_th_reg[18] <= cfg_wdata[2];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[19] <= 1'h1;
    else if (_215_) idle_base_th_reg[19] <= cfg_wdata[3];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[20] <= 1'h0;
    else if (_215_) idle_base_th_reg[20] <= cfg_wdata[4];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[21] <= 1'h1;
    else if (_215_) idle_base_th_reg[21] <= cfg_wdata[5];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[22] <= 1'h1;
    else if (_215_) idle_base_th_reg[22] <= cfg_wdata[6];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[23] <= 1'h1;
    else if (_215_) idle_base_th_reg[23] <= cfg_wdata[7];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[24] <= 1'h1;
    else if (_215_) idle_base_th_reg[24] <= cfg_wdata[8];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[25] <= 1'h1;
    else if (_215_) idle_base_th_reg[25] <= cfg_wdata[9];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[26] <= 1'h0;
    else if (_215_) idle_base_th_reg[26] <= cfg_wdata[10];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[27] <= 1'h0;
    else if (_215_) idle_base_th_reg[27] <= cfg_wdata[11];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[28] <= 1'h0;
    else if (_215_) idle_base_th_reg[28] <= cfg_wdata[12];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[29] <= 1'h0;
    else if (_215_) idle_base_th_reg[29] <= cfg_wdata[13];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[30] <= 1'h0;
    else if (_215_) idle_base_th_reg[30] <= cfg_wdata[14];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[0] <= 1'h0;
    else if (_216_) idle_base_th_reg[0] <= cfg_wdata[0];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[1] <= 1'h0;
    else if (_216_) idle_base_th_reg[1] <= cfg_wdata[1];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[2] <= 1'h0;
    else if (_216_) idle_base_th_reg[2] <= cfg_wdata[2];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[3] <= 1'h1;
    else if (_216_) idle_base_th_reg[3] <= cfg_wdata[3];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[4] <= 1'h0;
    else if (_216_) idle_base_th_reg[4] <= cfg_wdata[4];
  (* src = "../../cfg_regs.sv:80.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_base_th_reg[5] <= 1'h1;
    else if (_216_) idle_base_th_reg[5] <= cfg_wdata[5];
  (* src = "../../cfg_regs.sv:203.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) irq_status_reg[1] <= 1'h0;
    else if (_210_) irq_status_reg[1] <= _092_;
  (* src = "../../cfg_regs.sv:203.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) irq_status_reg[0] <= 1'h0;
    else if (_211_) irq_status_reg[0] <= _090_;
  (* src = "../../cfg_regs.sv:203.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) irq_status_reg[3] <= 1'h0;
    else if (_212_) irq_status_reg[3] <= _096_;
  assign \_355_$func$/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:519$11.a  = 2'hx;
  assign \_355_$func$/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:519$11.s  = 5'hxx;
  assign \_362_$func$/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:548$12.a  = 4'hx;
  assign \_362_$func$/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:548$12.b  = 20'hxxxxx;
  assign \_362_$func$/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:548$12.s  = 5'hxx;
  assign \_373_$func$/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:581$13.a  = 64'hxxxxxxxxxxxxxxxx;
  assign \_373_$func$/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:581$13.s  = 5'hxx;
  assign \_381_$func$/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:611$14.a  = 64'hxxxxxxxxxxxxxxxx;
  assign \_381_$func$/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:611$14.s  = 5'hxx;
  assign \_401_$func$/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:653$15.a  = 64'hxxxxxxxxxxxxxxxx;
  assign \_401_$func$/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:653$15.b  = 320'hxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx;
  assign \_401_$func$/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:653$15.s  = 5'hxx;
  assign \_423_$func$/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:697$16.a  = 12'hxxx;
  assign \_423_$func$/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:697$16.s  = 5'hxx;
  assign \_433_$func$/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:729$17.a  = 2'hx;
  assign \_433_$func$/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:729$17.s  = 5'hxx;
  assign \_441_$func$/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:759$18.a  = 14'hxxxx;
  assign \_441_$func$/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:759$18.s  = 5'hxx;
  assign \_451_$func$/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:791$19.a  = 16'hxxxx;
  assign \_451_$func$/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:791$19.s  = 5'hxx;
  assign \_459_$func$/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:821$20.a  = 2'hx;
  assign \_459_$func$/app/eda.work/d55a0a9b-8d3b-4608-a2c0-22957c86e4cf.edacmd/eda.work/cfg_regs.synth/slang/cfg_regs.v:821$20.s  = 5'hxx;
  assign alpha = alpha_reg;
  assign cfg_rdata[31:16] = 16'h0000;
  assign idle_base_th = idle_base_th_reg;
  assign periph_en = periph_en_reg;
  assign state_changed = { _096_, _094_, _092_, _090_ };
  assign wake_mask = wake_mask_reg;
endmodule
